import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/Layouts/Navbar";
import Footer from "@/component/Layouts/Footer";

export const poppins = Poppins({
  weight: ["300", "400", "500", "600", "700"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${poppins.className} antialiased`}>
        <header className="py-2 md:w-11/12 mx-auto">
          <Navbar></Navbar>
        </header>
        <main className="py-2 md:w-11/12 mx-auto">{children}</main>
        <footer className="py-2 md:w-11/12 mx-auto">
          <Footer></Footer>
        </footer>
      </body>
    </html>
  );
}
